<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_block_info() {
  $blocks['libhours'] = array(
    'info' => t('Library Hours'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_block_view() {

/**
 * Calling the css file
 */

drupal_add_css(drupal_get_path('module', 'libhours') . '/libhours.css');

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today'>";
  $mainEnd = "</ul>";

  $archRss = new DOMDocument();
  $archRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12309&format=xml&systemTime=1');
  $archHours = $archRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $archHours = "<div class='hours'>".$archHours."</div>";
  $archTitle = "<h3>Architecture Library</h3>";
  $archColor = $archRss->getElementsByTagName('color')->item(0)->nodeValue;
  $arch = "<li><a href='/architecture' class='library-hours-link' style='border-left:".$archColor." 35px solid'>".$archTitle.$archHours."</a></li>";

  $cdhRss = new DOMDocument();
  $cdhRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=14274&format=xml&systemTime=1');
  $cdhHours = $cdhRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $cdhHours = "<div class='hours'>".$cdhHours."</div>";
  $cdhTitle = "<h3>Center for Digital Humanities</h3>";
  $cdhColor = $cdhRss->getElementsByTagName('color')->item(0)->nodeValue;
  $cdh = "<li><a href='https://cdh.princeton.edu' class='library-hours-link' style='border-left:".$cdhColor." 35px solid'>".$cdhTitle.$cdhHours."</a></li>";

  $ealRss = new DOMDocument();
  $ealRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12310&format=xml&systemTime=1');
  $ealHours = $ealRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $ealHours = "<div class='hours'>".$ealHours."</div>";
  $ealTitle = "<h3>East Asian Library</h3>";
  $ealColor = $ealRss->getElementsByTagName('color')->item(0)->nodeValue;
  $eal = "<li><a href='/eastasian' class='library-hours-link' style='border-left:".$ealColor." 35px solid'>".$ealTitle.$ealHours."</a></li>";

  $engRss = new DOMDocument();
  $engRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=7899&format=xml&systemTime=1');
  $engHours = $engRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $engHours = "<div class='hours'>".$engHours."</div>";
  $engTitle = "<h3>Engineering Library</h3>";
  $engColor = "#3B7CCA";
  $eng = "<li><a href='/engineering' class='library-hours-link' style='border-left:".$engColor." 35px solid'>".$engTitle.$engHours."</a></li>";

  $fstRss = new DOMDocument();
  $fstRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=6975&format=xml&systemTime=1');
  $fstHours = $fstRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $fstHours = "<div class='hours'>".$fstHours."</div>";
  $fstTitle = "<h3>Firestone Library</h3>";
  $fstColor = $fstRss->getElementsByTagName('color')->item(0)->nodeValue;
  $fst = "<li><a href='/firestone' class='library-hours-link' style='border-left:".$fstColor." 35px solid'>".$fstTitle.$fstHours."</a></li>";

  $lewRss = new DOMDocument();
  $lewRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=7899&format=xml&systemTime=1');
  $lewHours = $lewRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $lewHours = "<div class='hours'>".$lewHours."</div>";
  $lewTitle = "<h3>Lewis Science Library</h3>";
  $lewColor = $lewRss->getElementsByTagName('color')->item(0)->nodeValue;
  $lew = "<li><a href='/lewis' class='library-hours-link' style='border-left:".$lewColor." 35px solid'>".$lewTitle.$lewHours."</a></li>";

  $marqRss = new DOMDocument();
  $marqRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=18259&format=xml&systemTime=1');
  $marqHours = $marqRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $marqHours = "<div class='hours'>".$marqHours."</div>";
  $marqTitle = "<h3>Marquand at Firestone</h3>";
  $marqColor = $marqRss->getElementsByTagName('color')->item(0)->nodeValue;
  $marq = "<li><a href='/marquand' class='library-hours-link' style='border-left:".$marqColor." 35px solid'>".$marqTitle.$marqHours."</a></li>";

  $mendRss = new DOMDocument();
  $mendRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12314&format=xml&systemTime=1');
  $mendHours = $mendRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $mendHours = "<div class='hours'>".$mendHours."</div>";
  $mendTitle = "<h3>Mendel Music Library</h3>";
  $mendColor = $mendRss->getElementsByTagName('color')->item(0)->nodeValue;
  $mend = "<li><a href='/music' class='library-hours-link' style='border-left:".$mendColor." 35px solid'>".$mendTitle.$mendHours."</a></li>";

  $muddRss = new DOMDocument();
  $muddRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12315&format=xml&systemTime=1');
  $muddHours = $muddRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $muddHours = "<div class='hours'>".$muddHours."</div>";
  $muddTitle = "<h3>Mudd Library</h3>";
  $muddColor = $muddRss->getElementsByTagName('color')->item(0)->nodeValue;
  $mudd = "<li><a href='/special-collections/mudd' class='library-hours-link' style='border-left:".$muddColor." 35px solid'>".$muddTitle.$muddHours."</a></li>";

  $scRss = new DOMDocument();
  $scRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=14275&format=xml&systemTime=1');
  $scHours = $scRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $scHours = "<div class='hours'>".$scHours."</div>";
  $scTitle = "<h3>Special Collections</h3>";
  $scColor = $scRss->getElementsByTagName('color')->item(0)->nodeValue;
  $sc = "<li><a href='/special-collections' class='library-hours-link' style='border-left:".$scColor." 35px solid'>".$scTitle.$scHours."</a></li>";

  $stokRss = new DOMDocument();
  $stokRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=7227&format=xml&systemTime=1');
  $stokHours = $stokRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $stokHours = "<div class='hours'>".$stokHours."</div>";
  $stokTitle = "<h3>Stokes Library</h3>";
  $stokColor = $stokRss->getElementsByTagName('color')->item(0)->nodeValue;
  $stok = "<li><a href='/stokes' class='library-hours-link' style='border-left:".$stokColor." 35px solid'>".$stokTitle.$stokHours."</a></li>";

  $moreHours = "<a href='https://libcal.princeton.edu/hours' class='views-more-link'>More Hours</a>";

  $hoursMain = $mainStart.$arch.$eal.$eng.$fst.$lew.$marq.$mend.$mudd.$sc.$stok.$moreHours.$mainEnd;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
