<?php


function catalog_block_form($form, &$form_state) {

  $form = array();
  $path = $_GET['q'];
  if(drupal_is_front_page()) { // should keyed off <front>
    $form_suffix = '<div class="homepage-tab-form-message"><a href="http://catalog.princeton.edu/">Main Catalog</a> <a href="http://princeton-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?mode=Advanced&vid=PRINCETON">Advanced Search</a></div>';
  } else {
    $form_suffix = "";
  }

  $form['query'] = array (
    '#type'  => 'textfield',
    '#title' =>  t('Search Catalog'),
    '#size'  => 80,
    '#default_value' => variable_get('catalog_search_hint'),
    '#attributes' => array(
        'placeholder' => variable_get('catalog_search_hint'),
    )
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
   );
   $form['sid'] = array(
     '#type' => 'hidden',
     '#value' => t("library-core"),
   );
    $form['#attached']['js'][] = drupal_get_path('module', 'catalog_block') .'/catalog_block.js';
    $hint_settings = array('catalog_search_hint' => variable_get('catalog_search_hint'),
                           'catalog_search_error' => variable_get('catalog_search_error')
                           );
    $form['#attached']['js'][] = array(
      'data' => array('catalog_block' => $hint_settings),
      'type' => 'setting',
     );
   $form['#action'] = url('/utils/search/location', array('external' => true));
   $form['#target'] = "_parent";
   $form['#method'] = "get";
   $form['#suffix'] = $form_suffix;
   return $form;

}

function catalog_block_form_validate($form, &$form_state) {
  $term = $form_state['values']['query'];
  if($term == "" || $term == variable_get('catalog_search_hint')) {
    form_set_error('term', t('Enter Search Terms'));
  }
}


function catalog_block_contents() {
  return drupal_get_form('catalog_block_form'); // must define a function
}

function catalog_block_get_current_filter($path) {
    $path_parts = explode("find/all/", $path);
    if(isset($path_parts[1])) {
        return filter_xss($path_parts[1]);
        return $path_parts[1];
    }
}

function catalog_block_query_escape($drupal_path) {
  $query = catalog_block_get_current_filter($drupal_path);
  return drupal_encode_path($query);
}

function  catalog_block_get_sid() {
    return "library-main";
}

function catalog_search_results_content() {
  $path = catalog_block_query_escape($_GET['q']);
  $sid = catalog_block_get_sid();
  $ajax_spinner = "<div id='catalog-search-results-spinner' class='results-spinner-large'><i class='icon-spinner icon-spin icon-refresh'></i></div>";
  $block_content = array(
    '#markup' => "<div data-source='/utils/find/any?query={$path}&sid={$sid}' id='catalog-search-results'>" . $ajax_spinner . t('') . "</div>",
  );
  return $block_content;
}

function catalog_journal_results_content() {
  $path = catalog_block_query_escape($_GET['q']);
  $sid = catalog_block_get_sid();
  $ajax_spinner = "<div id='journal-search-results-spinner' class='results-spinner-large'><i class='icon-spinner icon-spin icon-refresh'></i></div>";
  $block_content = array(
    '#markup' => "<div data-source='/utils/find/any?query={$path}&limit=exact&format=journals&sid={$sid}' id='journal-search-results'>" . $ajax_spinner . t('') . "</div>",
  );
  return $block_content;
}

function catalog_pulfa_results_content() {
  $path = catalog_block_query_escape($_GET['q']);
  $sid = catalog_block_get_sid();
  $ajax_spinner = "<div id='pulfa-search-results-spinner' class='results-spinner-large'><i class='icon-spinner icon-spin icon-refresh'></i></div>";
  $block_content = array(
    '#markup' => "<div data-source='/utils/pulfa/any?query={$path}&sid={$sid}' id='pulfa-search-results'>" . $ajax_spinner . t('') . "</div>",
  );
  return $block_content;
}

function catalog_pudl_results_content() {
  $path = catalog_block_query_escape($_GET['q']);
  $sid = catalog_block_get_sid();
  $ajax_spinner = "<div id='pudl-search-results-spinner' class='results-spinner-large'><i class='icon-spinner icon-spin icon-refresh icon-4x'></i></div>";
  $block_content = array(
    '#markup' => "<div data-source='/utils/pudl/any?query={$path}&sid={$sid}' id='pudl-search-results'>" . $ajax_spinner . t('') . "</div>",
  );
  return $block_content;
}

function catalog_faq_results_content() {
  $path = catalog_block_query_escape($_GET['q']);
  $sid = catalog_block_get_sid();
  $ajax_spinner = "<div id='faq-search-results-spinner' class='results-spinner-large'><i class='icon-spinner icon-spin icon-refresh icon-4x'></i></div>";
  $block_content = array(
    '#markup' => "<div data-source='/utils/faq/$path?sid={$sid}' id='faq-search-results'>" . $ajax_spinner . t('') . "</div>",
  );
  return $block_content;
}


/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.
 *
function catalog_block_menu() {
  $items['catalog_block'] = array(
    'page callback' => 'catalog_block_page',
    'access callback' => TRUE,
    'title' => 'Catalog Search',
  );
  return $items;
}
*/
/**
 * Implements hook_page()
 *
 */

function catalog_block_page() {

  $page = array(
    '#type' => 'markup',
    '#markup' => t('Configure The Books+ Search Box <a href="@url">the block admin page</a>.', array('@url' => url('admin/structure/block'))),
  );

  return $page;
}


/**
 * Implements hook_block_info()
 *
 */

function catalog_block_block_info() {

  $blocks['catalog_search'] = array(
      // info: The name of the block.
      'info' => t('Catalog Search'),
      // Block caching options (per role, per user, etc.)
      'cache' => DRUPAL_CACHE_PER_PAGE, // default
      'visibility' => BLOCK_VISIBILITY_LISTED,
   );
   $blocks['catalog_search_results'] = array(
      // block for search results from "books+" aka primo
      'info' => t('Books+ Search Results'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
   );
   $blocks['catalog_journal_results'] = array(
      'info' => t('Journal Results'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
   );
   $blocks['catalog_pulfa_results'] = array(
      'info' => t('Archives Results'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
   );
   $blocks['catalog_pudl_results'] = array(
      'info' => t('Princeton University Digital Library'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
   );
   $blocks['catalog_faq_results'] = array(
      'info' => t('FAQ Results'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
   );
   return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function catalog_block_block_configure($delta = '') {

  $form = array();
  if ($delta == 'catalog_search') { //in this case the delta is the name of block

    $form['catalog_search_hint'] = array(
      '#type' => 'textfield',
      '#title' => t('Search Box Hint Text'),
      '#size' => 60,
      '#description' => t('This text will appear as the hint when catalog search box is displayed.'),
      '#default_value' => variable_get('catalog_search_hint',  t('Hint you want to display.')),
    );
    $form['catalog_search_error'] = array(
      '#type' => 'textfield',
      '#title' => t('Invalid Search Error'),
      '#size' => 60,
      '#description' => t('This message will display when the user submits and empty search for the Books+ Block.'),
      '#default_value' => variable_get('catalog_search_error',  t('Supply a Books+ Search Term.')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * Make sure we can save the block
 */
function catalog_block_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  if ($delta == 'catalog_search') {
    // Have Drupal save the string to the database.
    variable_set('catalog_search_hint', $edit['catalog_search_hint']);
    variable_set('catalog_search_error', $edit['catalog_search_error']);
  }

  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function catalog_block_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.

  if ($delta == 'catalog_search') {
    $block['subject'] = t('Catalog Search');
    $block['content'] = catalog_block_contents($delta);

  } elseif ($delta == 'catalog_search_results') {
    $block['subject'] = t('Books+ Search Results');
    $block['content'] = catalog_search_results_content($delta);
    drupal_add_js(array('catalog_block' => array('request' => 'query')), 'setting');
    drupal_add_js(drupal_get_path('module', 'catalog_block') .'/catalog_search_results.js');
  } elseif ($delta == 'catalog_journal_results') {
    $block['subject'] = t('Journal Search Results');
    $block['content'] = catalog_journal_results_content($delta);
    drupal_add_js(drupal_get_path('module', 'catalog_block') .'/catalog_journal_results.js');
  } elseif ($delta == 'catalog_pulfa_results') {
    $block['subject'] = t('Library Archives Results');
    $block['content'] = catalog_pulfa_results_content($delta);
    drupal_add_js(drupal_get_path('module', 'catalog_block') .'/catalog_pulfa_results.js');
  } elseif ($delta == 'catalog_pudl_results') {
    $block['subject'] = t('Princeton University Digital Library');
    $block['content'] = catalog_pudl_results_content($delta);
    drupal_add_js(drupal_get_path('module', 'catalog_block') .'/catalog_pudl_results.js');
  } elseif ($delta == 'catalog_faq_results') {
    $block['subject'] = t('FAQ Results');
    $block['content'] = catalog_faq_results_content($delta);
    drupal_add_js(drupal_get_path('module', 'catalog_block') .'/catalog_faq_results.js');
  }
  return $block;
}
