<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_lewis_block_info() {
  $blocks['libhours_lewis'] = array(
    'info' => t('Library Hours - Lewis'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_lewis_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";

  $lewRss = new DOMDocument();
  $lewRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=7899&format=xml&systemTime=1');
  $lewHours = $lewRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $lew = "<li class='hours'><p>".$lewHours."</p><p class='seats'><a href='https://libcal.princeton.edu/seats?lid=3508'>Study-browse</a> and <a href='/services/book-pick-up'>Book Pick-up</a> services are available during these hours.</p></li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$lew.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
