<?php

/**
 * @file
 * Module to set messages for Princeton site authors
 */

/**
 * Implements hook_permission().
 */
function princeton_notices_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    'administer princeton messages' =>  array(
      'title' => t('Administer Princeton Messages'),
      'description' => t('Set notice texts for various PUL function'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function princeton_notices_menu() {

  $items['admin/princeton_notices'] = array(
    'title' => 'Manage Princeton Messages',
    'page callback' => 'princeton_notices_show_all',
    'page arguments' => array(),
    'access arguments' => array('administer princeton messages'),
    'type' => MENU_CALLBACK,
    //'file' => ,
  );
  $items['princeton_notices'] = array(
    'title' => 'Menu system examples',
    'description' => 'Menu system example that returns a string.',
    'page callback' => 'princeton_notices_show_page',
    'access callback' => TRUE,
    //'file' => ,
  );


  return $items;
}

function princeton_notices_show_page() {
  return "Page Text";
}

function princeton_notices_show_all() {
  $build = array(
    'string_paragraph' => array(
      '#type' => 'markup',
      '#markup' => '<p>Pages can be returned as strings.</p>',
    ),
    'render_array_paragraph' => array(
      '#type' => 'markup',
      '#markup' => '<p>Pages can be returned as <em>render arrays</em>.</p>',
    ),
    'why_render_arrays' => array(
      '#items' => array('They allow content to be modified as an array.', 'Arrays are a lot easier to modify than HTML.'),
      '#title' => 'Render arrays are better because...',
      '#theme' => 'item_list',
    ),
  );

  return $build;
}
