<?php


function dbsearch_block_form($form, &$form_state) {
    
  $form = array();

  $form['query'] = array (
    '#type'  => 'textfield',
    '#title' =>  t('Search Databases'),
    '#size'  => 40,
    '#default_value' => variable_get('db_search_hint')
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
   );
   //$form['#action'] = url('http://libwebprod.princeton.edu/searchit/search/location', array('external' => true));
   $form['#target'] = "_parent";
   $form['#method'] = "get";
   return $form;

}

function dbsearch_block_form_validate($form, &$form_state) {
  
  $term = $form_state['values']['query'];
  if($term == "" || $term == variable_get('db_search_hint')) {
    form_set_error('term', t('Enter Search Terms'));
  }
}

function dbsearch_block_contents() {
  return drupal_get_form('dbsearch_block_form'); // must define a function 
}




/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.
 */
function dbsearch_block_menu() {
  $items['dbsearch_block'] = array(
    'page callback' => 'dbsearch_block_page',
    'access callback' => TRUE,
    'title' => 'Catalog Search',
  );
  return $items;
}

/**
 * Implements hook_page()
 * 
 */
 
function dbsearch_block_page() {
    
  $page = array(
    '#type' => 'markup',
    '#markup' => t('Configure The Database Search Box <a href="@url">the block admin page</a>.', array('@url' => url('admin/structure/block'))),
  );
    
  return $page;
}


/**
 * Implements hook_block_info()
 * 
 */

function dbsearch_block_block_info() {
  
  $blocks['dbsearch_search'] = array(
      // info: The name of the block.
      'info' => t('Database Search'),
      // Block caching options (per role, per user, etc.)
      'cache' => DRUPAL_CACHE_PER_ROLE, // default
      'visibility' => BLOCK_VISIBILITY_LISTED,
   );
   
   return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function dbsearch_block_block_configure($delta = '') {
 
  $form = array();
  if ($delta == 'dbsearch_search') { //in this case the delta is the name of block

    $form['db_search_hint'] = array(
      '#type' => 'textfield',
      '#title' => t('Block contents'),
      '#size' => 60,
      '#description' => t('This text will appear as the hint when database search box is displayed.'),
      '#default_value' => variable_get('db_search_hint',  t('Hint you want to display.')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * Make sure we can save the block 
 */
function dbsearch_block_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  if ($delta == 'dbsearch_search') {
    // Have Drupal save the string to the database.
    variable_set('db_search_hint', $edit['db_search_hint']);
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function dbsearch_block_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  if ($delta == 'dbsearch_search') {
    $block['content'] = dbsearch_block_contents($delta);
  }
  drupal_add_css(drupal_get_path('module', 'dbsearch_block') .'/dbsearch_block.css');
  drupal_add_js(drupal_get_path('module', 'dbsearch_block') .'/dbsearch_block.js');
  
  return $block;
}




