name: library-main
recipe: drupal7
config:
  php: '7.4'
  webroot: .
  database: mariadb
services:
  search:
    type: solr:custom
    overrides:
      image: pulibrary/ci-solr:8.4-v1.0.0
      command: server/scripts/lando-start.sh
    core: libwww-dev
    portforward: 9999
    config:
      dir: sites/all/modules/search_api_solr/solr-conf/7.x
  cache:
    type: redis
    portforward: true
  node:
    type: 'node:11.15'
tooling:
  npm:
    service: node
  node:
    service: node
  redis-cli:
    service: cache
