name: library-main
recipe: drupal7
config:
  php: '7.2'
  webroot: .
services:
  search:
    type: 'solr:7'
    core: libwww-dev
    portforward: 9999
    config:
      dir: sites/all/modules/search_api_solr/solr-conf/7.x
  cache:
    type: redis
    portforward: true
  node:
    type: 'node:6.15'
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  redis-cli:
    service: cache
