name: library-main
recipe: drupal7
config:
  php: '8.0'
  webroot: .
  database: mariadb
  drush: '8.4.11'
services:
  search:
    type: solr:custom
    overrides:
      image: pulibrary/ci-solr:8.4-v1.0.0
      command: server/scripts/lando-start.sh
    core: libwww-dev
    portforward: 9999
    config:
      dir: sites/all/modules/search_api_solr/solr-conf/7.x
  cache:
    type: redis
    portforward: true
  node:
    type: 'node:14'
    overrides:
      platform: linux/amd64
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  redis-cli:
    service: cache
