<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_marquand_block_info() {
  $blocks['libhours_marquand'] = array(
    'info' => t('Library Hours - Marquand'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_marquand_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";

  $marqRss = new DOMDocument();
  $marqRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12313&format=xml&systemTime=1');
  $marqHours = $marqRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $marq = "<li class='hours'>".$marqHours."<div class='seats'><a href='https://libcal.princeton.edu/seats?lid=10656'>Study-browse service<br>Access by appointment only</a></div></li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$marq.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
