<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_video_block_info() {
  $blocks['libhours_video'] = array(
    'info' => t('Library Hours - Video Library'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_video_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";

  $videoRss = new DOMDocument();
  $videoRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=20083&format=xml&systemTime=1');
  $videoHours = $videoRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $video = "<li class='hours'>".$videoHours."</li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$video.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
