<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_makerspace_block_info() {
  $blocks['libhours_makerspace'] = array(
    'info' => t('Library Hours - Makerspace'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_makerspace_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";
  
  $makerRss = new DOMDocument();
  $makerRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=15700&format=xml&systemTime=1');
  $makerHours = $makerRss->getElementsByTagName('rendered')->item(2)->nodeValue;
  $makerPickUpHours = $makerRss->getElementsByTagName('rendered')->item(1)->nodeValue;
  $maker = "<li class='hours'>".$makerHours."<div class='seats'><a href='https://libcal.princeton.edu/reserve/makerspace'>Access by appointment only</a></div></li><li class='pickup-hours'>".$makerPickUpHours."<div><a href='https://libcal.princeton.edu/appointments?lid=387&g=12520'>Equipment / Consultations<br>Access by appointment only</a></div></li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$maker.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
