version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  stylelint:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '14'
      - node/install-packages:
          pkg-manager: npm
          app-dir: sites/all/themes/pul_base
      - run:
          command: npx stylelint assets/source/styles
          name: Lint SASS
          working_directory: sites/all/themes/pul_base
workflows:
  node:
    jobs:
      - stylelint
