<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_plasma_block_info() {
  $blocks['libhours_plasma'] = array(
    'info' => t('Library Hours - Plasma Physics'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_plasma_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";

  $pplRss = new DOMDocument();
  $pplRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12311&format=xml&systemTime=1');
  $pplHours = $pplRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $ppl = "<li class='hours'>".$pplTitle.$pplHours."</li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$ppl.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
