<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_firestone_block_info() {
  $blocks['libhours_firestone'] = array(
    'info' => t('Library Hours - Firestone'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_firestone_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";

  $fstRss = new DOMDocument();
  $fstRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=6975&format=xml&systemTime=1');
  $fstHours = $fstRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $fst = "<li class='hours'>".$fstHours."</li>";

  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$fst.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
