<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_ask_block_info() {
  $blocks['libhours_ask'] = array(
    'info' => t('Library Hours - Ask a Librarian'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_ask_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";
  
  $askRss = new DOMDocument();
  $askRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12293&format=xml&systemTime=1');
  $askHours = $askRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $ask = "<li class='hours'>".$askHours."</li>";

  $moreHours = "<a href='https://libcal.princeton.edu/hours' class='views-more-link'>More Hours</a>";
  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$ask.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
