<?php
/**
 * @file
 * library_news.flexslider_default_preset.inc
 */

/**
 * Implements hook_flexslider_default_presets().
 */
function library_news_flexslider_default_presets() {
  $export = array();

  $preset = new stdClass();
  $preset->disabled = FALSE; /* Edit this to true to make a default preset disabled initially */
  $preset->api_version = 1;
  $preset->name = 'library_spotlight';
  $preset->title = 'Library Spotlight';
  $preset->theme = 'classic';
  $preset->imagestyle_normal = 'large';
  $preset->options = array(
    'animation' => 'fade',
    'animationDuration' => 600,
    'slideDirection' => 'horizontal',
    'slideshow' => 1,
    'slideshowSpeed' => 7000,
    'animationLoop' => 1,
    'randomize' => 0,
    'slideToStart' => 0,
    'directionNav' => 1,
    'controlNav' => 1,
    'keyboardNav' => 1,
    'mousewheel' => 1,
    'prevText' => 'Previous',
    'nextText' => 'Next',
    'pausePlay' => 0,
    'pauseText' => 'Pause',
    'playText' => 'Play',
    'pauseOnAction' => 1,
    'controlsContainer' => '.flex-nav-container',
    'manualControls' => '.flex-control-nav li',
  );
  $export['library_spotlight'] = $preset;

  return $export;
}
