<?php

/**
 * @file
 * Create a search block
 */

/**
 * Implements hook_block_info().
 */
function libhours_architecture_block_info() {
  $blocks['libhours_architecture'] = array(
    'info' => t('Library Hours - Architecture'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libhours_architecture_block_view() {

/**
 * Block content
 */

  $mainStart = "<ul class='hours--today__branch links--decorate'>";
  $mainEnd = "</ul>";
  
  $archRss = new DOMDocument();
  $archRss->load('https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12309&format=xml&systemTime=1');
  $archHours = $archRss->getElementsByTagName('rendered')->item(0)->nodeValue;
  $arch = "<li class='hours'><p>".$archHours."</p><p class='seats'><a href='https://libcal.princeton.edu/seats?lid=10655'>Study-browse</a> and <a href='/services/book-pick-up'>Book Pick-up</a> services are available during these hours.</p></li>";

  $moreHours = "<a href='https://libcal.princeton.edu/hours' class='views-more-link'>More Hours</a>";
  $fullSchedule = "<p>For summer, holidays or recess hours, please consult the <a href='https://libcal.princeton.edu/hours'>full schedule</a>.</p>";
  
  $hoursMain = $mainStart.$arch.$mainEnd.$fullSchedule;

  $content = $hoursMain;
  $block = array(
    'subject' => t("Today's Hours"),
    'content' => $content,
  );
  return $block;

}
