<?php
function allsearch_block_get_current_filter($path) {
  $path_parts = explode("find/all/", $path);
  if(isset($path_parts[1])) {
    return $path_parts[1];
  }
}

function allsearch_block_form($form, &$form_state) {
  $path = allsearch_block_get_current_filter($_GET['q']);
  
  if(isset($path)) {
    $default_value = $path;
  } else {
    $default_value = variable_get('all_search_hint');
  }
  
  $form = array();

  $form['query'] = array (
    '#type'  => 'textfield',
    '#title' =>  t('All Search'),
    '#size'  => 40,
    '#required' => TRUE,
    '#default_value' => $default_value
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
   );
   $form['#validate'] = array('allsearch_block_form_validate');
   $form['#submit'] = array('allsearch_block_form_redirect');
   $form['#method'] = "post";
   return $form;

}

function allsearch_block_form_redirect($form, &$form_state) {
  $form_state['redirect'] = 'find/all/' . $form_state['values']['query'];
}

function allsearch_block_form_validate($form, &$form_state) {
  
  $term = $form_state['values']['query'];
  if($term == "" || $term == variable_get('all_search_hint')) {
    form_set_error('term', t('What do you want to search for?'));
  }
}

//function allsearch_block_form_submit($form, &$form_state) {
//  drupal_set_message(t('Submitting values: @values', array('@values' => var_export($form_state['values'], TRUE))));
//}


function allsearch_block_contents() {
  return drupal_get_form('allsearch_block_form'); // must define a function 
}




/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.

function allsearch_block_menu() {
  $items['allsearch_block'] = array(
    'page callback' => 'allsearch_block_page',
    'access callback' => TRUE,
    'title' => 'Catalog Search',
  );
  return $items;
}
*/
/**
 * Implements hook_page()
 * 
 */
 
function allsearch_block_page() {
    
  $page = array(
    '#type' => 'markup',
    '#markup' => t('Configure The All Search Box <a href="@url">the block admin page</a>.', array('@url' => url('admin/structure/block'))),
  );
    
  return $page;
}


/**
 * Implements hook_block_info()
 * 
 */

function allsearch_block_block_info() {
  
  $blocks['allsearch_search'] = array(
      // info: The name of the block.
      'info' => t('All Search'),
      // Block caching options (per role, per user, etc.)
      'cache' => DRUPAL_CACHE_PER_ROLE, // default
      'visibility' => BLOCK_VISIBILITY_LISTED,
   );
   
   return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function allsearch_block_block_configure($delta = '') {
 
  $form = array();
  if ($delta == 'allsearch_search') { //in this case the delta is the name of block

    $form['all_search_hint'] = array(
      '#type' => 'textfield',
      '#title' => t('Block contents'),
      '#size' => 60,
      '#description' => t('This text will appear as the hint when catalog search box is displayed.'),
      '#default_value' => variable_get('all_search_hint',  t('Hint you want to display.')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * Make sure we can save the block 
 */
function allsearch_block_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  if ($delta == 'allsearch_search') {
    // Have Drupal save the string to the database.
    variable_set('all_search_hint', $edit['all_search_hint']);
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function allsearch_block_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  if ($delta == 'allsearch_search') {
    $block['subject'] = t('All Search');
    $block['content'] = allsearch_block_contents($delta);
  }
  // add css block
  drupal_add_css(drupal_get_path('module', 'allsearch_block') .'/allsearch_block.css');
  drupal_add_js(drupal_get_path('module', 'allsearch_block') .'/allsearch_block.js');
  return $block;
}




