<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
module_load_include('inc', 'ezproxy_utils', 'ezproxy_utils.drush.inc');

function ezproxy_utils_get_domain($url) {
    
    //preg_match("/^(https?:\/\/)?([^\/]+)/i", $url, $matches);
    //$domain = $matches[2];
    // get last two segments of host name
    //preg_match("/[^\.\/]+\.[^\.\/]+$/", $domain, $matches);
    //if($matches[0] == "co.uk" || $matches[0] == "ac.uk") {
    // do nothing
    //                            } else {
    //return $matches[0];
    $url_components = parse_url($url);
    return $url_components['host'];

}