<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
module_load_include('inc', 'ezproxy_utils', 'ezproxy_utils.drush.inc');

function ezproxy_utils_get_domain($url) {
    
    $url_components = parse_url($url);
    return $url_components['host'];

}

function ezproxy_utils_trim_field($field, $num_of_chars = 500) {

    if (strlen($field) > $num_of_chars) {
        $field_value = preg_replace('/\s+?(\S+)?$/', '', substr($field, 0, $num_of_chars));
        drush_print("trimming");
        return $field_value;
    } else {
        return $field;
    }
}